# Generated by Django 2.2 on 2019-04-21 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driverAPI', '0001_initial'),
        ('passengerAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverrideshistory',
            name='passenger_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passengerAPI.Passenger'),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='driver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driverAPI.Driver'),
        ),
    ]
